server:
  port: 8101

spring:
  application:
    name: consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.86.182:3306/mydb?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimeZone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  zipkin:
    base-url: http://123.57.86.182:9411
  sleuth:
      sampler:
        probability: 1
        rate: 30   # 30s采集一次


