server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: producer_route
        uri: lb://producer/
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1  #查找服务去掉 /api
        - name: RequestRateLimiter  #限流
          args:
            key-resolver: '#{@hostAddrKeyResolver}'  #注入bean
            redis-rate-limiter.replenishRate: 1   # 每秒填充速率
            redis-rate-limiter.burstCapacity: 20   # 桶的容量
      - id: consumer_route
        uri: lb://consumer/
        predicates:
        - Path=/**
        filters:
        - PrefixPath=/consumer #查找服务自定加上/consumer
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.124.9
    port: 6379
    database: 0

logging:
  level:
    org.springframework.cloud.gateway: debug

