server:
  port: 9998
spring:
  application:
    name: zuul
zuul:
  routes:
    producerapi:
      path: /proapi/**
      serviceId: producer
    consumerapi:
      path: /conapi/**
      serviceId: consumer