server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: producer_route
        uri: lb://producer/
        predicates:
        - Path=/prodapi/**
        filters:
        - StripPrefix=1
      - id: consumer_route
        uri: lb://consumer/
        predicates:
        - Path=/conapi/**
        filters:
        - StripPrefix=0
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

eureka:
  instance:
    hostname: gateway
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

