server:
  port: 8001

spring:
  application:
    name: producer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.9:3306/mydb?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimeZone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    zookeeper:
      connect-string: 192.168.124.9:2181